// Promedic Products Database - 150 SKUs
const PROMEDIC_PRODUCTS = [
  // ===== PRESCRIPTION (Rx) =====
  { id: 1, name: "Amoxicillin 500mg", category: "rx", subcategory: "Antibiotics", price: 18.99, originalPrice: 28.00, emoji: "💊", desc: "Broad-spectrum antibiotic for bacterial infections. Requires valid prescription.", requires_rx: true, rating: 4.8, reviews: 312, sku: "RX-001", inStock: true, tags: ["antibiotic", "infection"] },
  { id: 2, name: "Lisinopril 10mg", category: "rx", subcategory: "Blood Pressure", price: 12.99, originalPrice: 22.00, emoji: "💊", desc: "ACE inhibitor for high blood pressure management. Requires valid prescription.", requires_rx: true, rating: 4.7, reviews: 245, sku: "RX-002", inStock: true, tags: ["hypertension", "heart"] },
  { id: 3, name: "Metformin 500mg", category: "rx", subcategory: "Diabetes", price: 14.99, originalPrice: 24.00, emoji: "💊", desc: "First-line medication for type 2 diabetes management.", requires_rx: true, rating: 4.9, reviews: 480, sku: "RX-003", inStock: true, tags: ["diabetes", "blood sugar"] },
  { id: 4, name: "Atorvastatin 20mg", category: "rx", subcategory: "Cholesterol", price: 16.99, originalPrice: 26.00, emoji: "💊", desc: "Statin medication to lower LDL cholesterol and reduce cardiovascular risk.", requires_rx: true, rating: 4.7, reviews: 198, sku: "RX-004", inStock: true, tags: ["cholesterol", "heart"] },
  { id: 5, name: "Sertraline 50mg", category: "rx", subcategory: "Mental Health", price: 22.99, originalPrice: 35.00, emoji: "💊", desc: "SSRI antidepressant for depression and anxiety disorders.", requires_rx: true, rating: 4.6, reviews: 167, sku: "RX-005", inStock: true, tags: ["depression", "anxiety"] },
  { id: 6, name: "Omeprazole 20mg Rx", category: "rx", subcategory: "Gastro", price: 15.99, originalPrice: 28.00, emoji: "💊", desc: "Proton pump inhibitor for severe acid reflux and ulcers.", requires_rx: true, rating: 4.8, reviews: 221, sku: "RX-006", inStock: true, tags: ["acid reflux", "gastro"] },
  { id: 7, name: "Azithromycin 250mg", category: "rx", subcategory: "Antibiotics", price: 24.99, originalPrice: 38.00, emoji: "💊", desc: "Macrolide antibiotic for respiratory and skin infections.", requires_rx: true, rating: 4.7, reviews: 290, sku: "RX-007", inStock: true, tags: ["antibiotic", "respiratory"] },
  { id: 8, name: "Levothyroxine 50mcg", category: "rx", subcategory: "Thyroid", price: 13.99, originalPrice: 22.00, emoji: "💊", desc: "Synthetic thyroid hormone for hypothyroidism treatment.", requires_rx: true, rating: 4.9, reviews: 342, sku: "RX-008", inStock: true, tags: ["thyroid", "hormone"] },
  { id: 9, name: "Amlodipine 5mg", category: "rx", subcategory: "Blood Pressure", price: 11.99, originalPrice: 20.00, emoji: "💊", desc: "Calcium channel blocker for hypertension and chest pain.", requires_rx: true, rating: 4.6, reviews: 156, sku: "RX-009", inStock: true, tags: ["blood pressure", "heart"] },
  { id: 10, name: "Metoprolol 25mg", category: "rx", subcategory: "Blood Pressure", price: 13.99, originalPrice: 21.00, emoji: "💊", desc: "Beta-blocker for high blood pressure and heart failure.", requires_rx: true, rating: 4.7, reviews: 178, sku: "RX-010", inStock: true, tags: ["beta-blocker", "heart"] },
  { id: 11, name: "Gabapentin 300mg", category: "rx", subcategory: "Neurology", price: 19.99, originalPrice: 32.00, emoji: "💊", desc: "Anticonvulsant for seizures and neuropathic pain.", requires_rx: true, rating: 4.5, reviews: 134, sku: "RX-011", inStock: true, tags: ["nerve pain", "seizure"] },
  { id: 12, name: "Hydrochlorothiazide 25mg", category: "rx", subcategory: "Blood Pressure", price: 10.99, originalPrice: 18.00, emoji: "💊", desc: "Diuretic for high blood pressure and edema.", requires_rx: true, rating: 4.6, reviews: 112, sku: "RX-012", inStock: true, tags: ["diuretic", "blood pressure"] },
  { id: 13, name: "Prednisone 10mg", category: "rx", subcategory: "Steroids", price: 17.99, originalPrice: 28.00, emoji: "💊", desc: "Corticosteroid for inflammatory and autoimmune conditions.", requires_rx: true, rating: 4.5, reviews: 98, sku: "RX-013", inStock: true, tags: ["inflammation", "steroid"] },
  { id: 14, name: "Losartan 50mg", category: "rx", subcategory: "Blood Pressure", price: 15.99, originalPrice: 25.00, emoji: "💊", desc: "ARB for hypertension and kidney protection in diabetes.", requires_rx: true, rating: 4.7, reviews: 189, sku: "RX-014", inStock: true, tags: ["ARB", "blood pressure"] },
  { id: 15, name: "Clopidogrel 75mg", category: "rx", subcategory: "Cardiology", price: 21.99, originalPrice: 34.00, emoji: "💊", desc: "Antiplatelet for prevention of blood clots.", requires_rx: true, rating: 4.8, reviews: 143, sku: "RX-015", inStock: true, tags: ["blood clot", "cardiology"] },
  { id: 16, name: "Albuterol Inhaler", category: "rx", subcategory: "Respiratory", price: 29.99, originalPrice: 45.00, emoji: "🫁", desc: "Fast-acting bronchodilator for asthma and COPD relief.", requires_rx: true, rating: 4.9, reviews: 390, sku: "RX-016", inStock: true, tags: ["asthma", "inhaler"] },
  { id: 17, name: "Fluticasone Inhaler", category: "rx", subcategory: "Respiratory", price: 34.99, originalPrice: 55.00, emoji: "🫁", desc: "Inhaled corticosteroid for asthma prevention.", requires_rx: true, rating: 4.7, reviews: 215, sku: "RX-017", inStock: true, tags: ["asthma", "steroid inhaler"] },
  { id: 18, name: "Warfarin 5mg", category: "rx", subcategory: "Cardiology", price: 14.99, originalPrice: 24.00, emoji: "💊", desc: "Anticoagulant for preventing dangerous blood clots.", requires_rx: true, rating: 4.6, reviews: 87, sku: "RX-018", inStock: true, tags: ["anticoagulant", "blood thinner"] },
  { id: 19, name: "Pantoprazole 40mg", category: "rx", subcategory: "Gastro", price: 18.99, originalPrice: 30.00, emoji: "💊", desc: "PPI for erosive esophagitis and Zollinger-Ellison syndrome.", requires_rx: true, rating: 4.7, reviews: 165, sku: "RX-019", inStock: true, tags: ["PPI", "gastro"] },
  { id: 20, name: "Ciprofloxacin 500mg", category: "rx", subcategory: "Antibiotics", price: 22.99, originalPrice: 36.00, emoji: "💊", desc: "Fluoroquinolone antibiotic for urinary and respiratory infections.", requires_rx: true, rating: 4.6, reviews: 201, sku: "RX-020", inStock: true, tags: ["antibiotic", "UTI"] },
  { id: 21, name: "Escitalopram 10mg", category: "rx", subcategory: "Mental Health", price: 19.99, originalPrice: 32.00, emoji: "💊", desc: "SSRI for major depressive disorder and generalized anxiety.", requires_rx: true, rating: 4.8, reviews: 178, sku: "RX-021", inStock: true, tags: ["SSRI", "anxiety"] },
  { id: 22, name: "Rosuvastatin 10mg", category: "rx", subcategory: "Cholesterol", price: 18.99, originalPrice: 30.00, emoji: "💊", desc: "High-potency statin for cholesterol and triglyceride management.", requires_rx: true, rating: 4.7, reviews: 132, sku: "RX-022", inStock: true, tags: ["statin", "cholesterol"] },
  { id: 23, name: "Doxycycline 100mg", category: "rx", subcategory: "Antibiotics", price: 20.99, originalPrice: 33.00, emoji: "💊", desc: "Tetracycline antibiotic for Lyme disease, acne, and more.", requires_rx: true, rating: 4.7, reviews: 225, sku: "RX-023", inStock: true, tags: ["antibiotic", "Lyme"] },
  { id: 24, name: "Tamsulosin 0.4mg", category: "rx", subcategory: "Urology", price: 16.99, originalPrice: 27.00, emoji: "💊", desc: "Alpha-blocker for benign prostatic hyperplasia symptoms.", requires_rx: true, rating: 4.6, reviews: 119, sku: "RX-024", inStock: true, tags: ["BPH", "prostate"] },
  { id: 25, name: "Methotrexate 2.5mg", category: "rx", subcategory: "Immunology", price: 25.99, originalPrice: 40.00, emoji: "💊", desc: "Disease-modifying drug for rheumatoid arthritis and psoriasis.", requires_rx: true, rating: 4.5, reviews: 76, sku: "RX-025", inStock: true, tags: ["rheumatoid", "immunology"] },

  // ===== OTC =====
  { id: 26, name: "Ibuprofen 200mg (100ct)", category: "otc", subcategory: "Pain Relief", price: 8.99, originalPrice: 13.00, emoji: "💊", desc: "NSAID for pain, fever, and inflammation relief.", requires_rx: false, rating: 4.9, reviews: 670, sku: "OTC-001", inStock: true, tags: ["pain", "fever", "NSAID"] },
  { id: 27, name: "Acetaminophen 500mg (100ct)", category: "otc", subcategory: "Pain Relief", price: 7.99, originalPrice: 12.00, emoji: "💊", desc: "Gentle pain and fever reliever safe for most adults.", requires_rx: false, rating: 4.9, reviews: 890, sku: "OTC-002", inStock: true, tags: ["pain", "fever", "Tylenol"] },
  { id: 28, name: "Naproxen 220mg (80ct)", category: "otc", subcategory: "Pain Relief", price: 9.99, originalPrice: 15.00, emoji: "💊", desc: "Long-lasting NSAID for arthritis and pain. 12-hour relief.", requires_rx: false, rating: 4.7, reviews: 312, sku: "OTC-003", inStock: true, tags: ["pain", "arthritis", "Aleve"] },
  { id: 29, name: "Aspirin 325mg (100ct)", category: "otc", subcategory: "Pain/Cardio", price: 6.99, originalPrice: 10.00, emoji: "💊", desc: "Pain reliever and daily low-dose cardioprotective therapy.", requires_rx: false, rating: 4.8, reviews: 445, sku: "OTC-004", inStock: true, tags: ["pain", "aspirin", "heart"] },
  { id: 30, name: "Omeprazole OTC 20mg (42ct)", category: "otc", subcategory: "Digestive Health", price: 14.99, originalPrice: 22.00, emoji: "💊", desc: "14-day course for frequent heartburn. Prilosec equivalent.", requires_rx: false, rating: 4.8, reviews: 380, sku: "OTC-005", inStock: true, tags: ["heartburn", "GERD", "PPI"] },
  { id: 31, name: "Loratadine 10mg (30ct)", category: "otc", subcategory: "Allergy", price: 8.99, originalPrice: 14.00, emoji: "💊", desc: "Non-drowsy 24-hour allergy relief. Claritin equivalent.", requires_rx: false, rating: 4.9, reviews: 520, sku: "OTC-006", inStock: true, tags: ["allergy", "antihistamine"] },
  { id: 32, name: "Cetirizine 10mg (45ct)", category: "otc", subcategory: "Allergy", price: 9.99, originalPrice: 16.00, emoji: "💊", desc: "Once-daily 24-hour allergy symptom relief. Zyrtec equivalent.", requires_rx: false, rating: 4.8, reviews: 467, sku: "OTC-007", inStock: true, tags: ["allergy", "antihistamine"] },
  { id: 33, name: "Diphenhydramine 25mg (24ct)", category: "otc", subcategory: "Allergy/Sleep", price: 6.99, originalPrice: 11.00, emoji: "💊", desc: "Nighttime allergy relief and sleep aid. Benadryl equivalent.", requires_rx: false, rating: 4.7, reviews: 298, sku: "OTC-008", inStock: true, tags: ["allergy", "sleep"] },
  { id: 34, name: "Mucinex 400mg (20ct)", category: "otc", subcategory: "Cold & Flu", price: 11.99, originalPrice: 18.00, emoji: "💊", desc: "Expectorant to relieve chest congestion and mucus.", requires_rx: false, rating: 4.7, reviews: 356, sku: "OTC-009", inStock: true, tags: ["congestion", "cold", "mucus"] },
  { id: 35, name: "NyQuil Cold & Flu (12oz)", category: "otc", subcategory: "Cold & Flu", price: 12.99, originalPrice: 19.00, emoji: "🍶", desc: "Nighttime multi-symptom cold and flu relief liquid.", requires_rx: false, rating: 4.8, reviews: 423, sku: "OTC-010", inStock: true, tags: ["cold", "flu", "nighttime"] },
  { id: 36, name: "DayQuil Liquicaps (24ct)", category: "otc", subcategory: "Cold & Flu", price: 11.99, originalPrice: 18.00, emoji: "💊", desc: "Non-drowsy daytime cold and flu multi-symptom relief.", requires_rx: false, rating: 4.7, reviews: 389, sku: "OTC-011", inStock: true, tags: ["cold", "flu", "daytime"] },
  { id: 37, name: "Antacid Calcium Chews (100ct)", category: "otc", subcategory: "Digestive Health", price: 9.99, originalPrice: 15.00, emoji: "🍬", desc: "Fast-acting calcium carbonate antacid for heartburn relief.", requires_rx: false, rating: 4.8, reviews: 334, sku: "OTC-012", inStock: true, tags: ["heartburn", "antacid", "calcium"] },
  { id: 38, name: "Gas Relief Extra Strength (40ct)", category: "otc", subcategory: "Digestive Health", price: 8.99, originalPrice: 14.00, emoji: "💊", desc: "Simethicone for rapid relief from gas and bloating.", requires_rx: false, rating: 4.6, reviews: 198, sku: "OTC-013", inStock: true, tags: ["gas", "bloating", "digestion"] },
  { id: 39, name: "Hydrocortisone Cream 1%", category: "otc", subcategory: "Skin", price: 7.99, originalPrice: 12.00, emoji: "🧴", desc: "Topical steroid cream for eczema, itching, and rashes.", requires_rx: false, rating: 4.7, reviews: 267, sku: "OTC-014", inStock: true, tags: ["skin", "eczema", "itch"] },
  { id: 40, name: "Clotrimazole Cream 1%", category: "otc", subcategory: "Antifungal", price: 9.99, originalPrice: 15.00, emoji: "🧴", desc: "Antifungal cream for athlete's foot, ringworm, and jock itch.", requires_rx: false, rating: 4.7, reviews: 178, sku: "OTC-015", inStock: true, tags: ["antifungal", "skin"] },
  { id: 41, name: "Neosporin Triple Antibiotic", category: "otc", subcategory: "First Aid", price: 8.99, originalPrice: 14.00, emoji: "🧴", desc: "First aid antibiotic ointment to help prevent infection.", requires_rx: false, rating: 4.9, reviews: 512, sku: "OTC-016", inStock: true, tags: ["first aid", "wound", "antibiotic"] },
  { id: 42, name: "Loperamide 2mg (24ct)", category: "otc", subcategory: "Digestive Health", price: 7.99, originalPrice: 12.00, emoji: "💊", desc: "Fast-acting anti-diarrheal medication. Imodium equivalent.", requires_rx: false, rating: 4.7, reviews: 223, sku: "OTC-017", inStock: true, tags: ["diarrhea", "digestive"] },
  { id: 43, name: "MiraLax Laxative (30 doses)", category: "otc", subcategory: "Digestive Health", price: 15.99, originalPrice: 24.00, emoji: "💊", desc: "Osmotic laxative for gentle, comfortable constipation relief.", requires_rx: false, rating: 4.8, reviews: 345, sku: "OTC-018", inStock: true, tags: ["constipation", "laxative"] },
  { id: 44, name: "Meclizine 25mg (30ct)", category: "otc", subcategory: "Motion Sickness", price: 9.99, originalPrice: 15.00, emoji: "💊", desc: "Antihistamine for motion sickness and vertigo relief.", requires_rx: false, rating: 4.6, reviews: 156, sku: "OTC-019", inStock: true, tags: ["motion sickness", "vertigo"] },
  { id: 45, name: "Eye Drops Lubricant 0.5oz", category: "otc", subcategory: "Eye Care", price: 8.99, originalPrice: 13.00, emoji: "👁️", desc: "Preservative-free artificial tears for dry eye relief.", requires_rx: false, rating: 4.8, reviews: 289, sku: "OTC-020", inStock: true, tags: ["dry eye", "eye drops"] },
  { id: 46, name: "Nicotine Patch 14mg (14ct)", category: "otc", subcategory: "Smoking Cessation", price: 29.99, originalPrice: 45.00, emoji: "🩹", desc: "Step 2 nicotine replacement therapy patch for quitting smoking.", requires_rx: false, rating: 4.5, reviews: 134, sku: "OTC-021", inStock: true, tags: ["quit smoking", "nicotine"] },
  { id: 47, name: "Phenylephrine Nasal Spray", category: "otc", subcategory: "Nasal Care", price: 8.99, originalPrice: 13.00, emoji: "💨", desc: "Fast relief from nasal congestion. No drowsiness.", requires_rx: false, rating: 4.6, reviews: 198, sku: "OTC-022", inStock: true, tags: ["nasal", "congestion", "sinus"] },
  { id: 48, name: "Saline Nasal Spray", category: "otc", subcategory: "Nasal Care", price: 6.99, originalPrice: 10.00, emoji: "💨", desc: "Gentle saline rinse to moisturize and relieve sinus symptoms.", requires_rx: false, rating: 4.8, reviews: 245, sku: "OTC-023", inStock: true, tags: ["nasal", "saline", "sinus"] },
  { id: 49, name: "Zinc Oxide Sunscreen SPF 50", category: "otc", subcategory: "Skin Care", price: 14.99, originalPrice: 22.00, emoji: "☀️", desc: "Broad-spectrum mineral sunscreen. Water-resistant, reef-safe.", requires_rx: false, rating: 4.7, reviews: 312, sku: "OTC-024", inStock: true, tags: ["sunscreen", "skin", "SPF"] },
  { id: 50, name: "Miconazole Vaginal Cream 2%", category: "otc", subcategory: "Women's Health", price: 11.99, originalPrice: 18.00, emoji: "🧴", desc: "Antifungal treatment for vaginal yeast infections.", requires_rx: false, rating: 4.6, reviews: 167, sku: "OTC-025", inStock: true, tags: ["yeast infection", "antifungal"] },

  // ===== SUPPLEMENTS =====
  { id: 51, name: "Omega-3 Fish Oil 1000mg (90ct)", category: "supplement", subcategory: "Heart Health", price: 18.99, originalPrice: 28.00, emoji: "🐟", desc: "Triple-strength EPA/DHA for heart, brain, and joint health.", requires_rx: false, rating: 4.9, reviews: 789, sku: "SUP-001", inStock: true, tags: ["omega-3", "heart", "brain"] },
  { id: 52, name: "Vitamin D3 5000 IU (120ct)", category: "supplement", subcategory: "Vitamins", price: 14.99, originalPrice: 22.00, emoji: "☀️", desc: "High-potency vitamin D3 for immune support and bone health.", requires_rx: false, rating: 4.9, reviews: 945, sku: "SUP-002", inStock: true, tags: ["vitamin D", "immune", "bone"] },
  { id: 53, name: "Magnesium Glycinate 400mg (90ct)", category: "supplement", subcategory: "Minerals", price: 22.99, originalPrice: 34.00, emoji: "💊", desc: "Highly bioavailable magnesium for sleep, stress, and muscle function.", requires_rx: false, rating: 4.8, reviews: 567, sku: "SUP-003", inStock: true, tags: ["magnesium", "sleep", "muscle"] },
  { id: 54, name: "Probiotics 50 Billion CFU (30ct)", category: "supplement", subcategory: "Digestive", price: 29.99, originalPrice: 44.00, emoji: "🦠", desc: "12-strain probiotic blend for gut microbiome and immune health.", requires_rx: false, rating: 4.8, reviews: 456, sku: "SUP-004", inStock: true, tags: ["probiotics", "gut", "immune"] },
  { id: 55, name: "Multivitamin Men's (90ct)", category: "supplement", subcategory: "Multivitamins", price: 24.99, originalPrice: 37.00, emoji: "💊", desc: "Complete daily nutrition for men with 25+ vitamins and minerals.", requires_rx: false, rating: 4.7, reviews: 389, sku: "SUP-005", inStock: true, tags: ["multivitamin", "men", "daily"] },
  { id: 56, name: "Multivitamin Women's (90ct)", category: "supplement", subcategory: "Multivitamins", price: 24.99, originalPrice: 37.00, emoji: "💊", desc: "Complete daily nutrition for women with iron and folate.", requires_rx: false, rating: 4.8, reviews: 423, sku: "SUP-006", inStock: true, tags: ["multivitamin", "women", "iron"] },
  { id: 57, name: "Vitamin C 1000mg (100ct)", category: "supplement", subcategory: "Vitamins", price: 12.99, originalPrice: 20.00, emoji: "🍊", desc: "High-dose vitamin C with rose hip for immune support.", requires_rx: false, rating: 4.9, reviews: 678, sku: "SUP-007", inStock: true, tags: ["vitamin C", "immune", "antioxidant"] },
  { id: 58, name: "Zinc 50mg (60ct)", category: "supplement", subcategory: "Minerals", price: 9.99, originalPrice: 16.00, emoji: "💊", desc: "Immune-boosting zinc for immune defense and wound healing.", requires_rx: false, rating: 4.7, reviews: 345, sku: "SUP-008", inStock: true, tags: ["zinc", "immune", "wound"] },
  { id: 59, name: "Melatonin 5mg (90ct)", category: "supplement", subcategory: "Sleep", price: 13.99, originalPrice: 21.00, emoji: "🌙", desc: "Natural sleep hormone to regulate sleep-wake cycles.", requires_rx: false, rating: 4.8, reviews: 534, sku: "SUP-009", inStock: true, tags: ["sleep", "melatonin", "insomnia"] },
  { id: 60, name: "Collagen Peptides 20g (30sv)", category: "supplement", subcategory: "Beauty/Joints", price: 34.99, originalPrice: 50.00, emoji: "💪", desc: "Hydrolyzed Type I & III collagen for skin, joints, and hair.", requires_rx: false, rating: 4.8, reviews: 467, sku: "SUP-010", inStock: true, tags: ["collagen", "skin", "joints"] },
  { id: 61, name: "Ashwagandha 600mg KSM-66 (60ct)", category: "supplement", subcategory: "Adaptogen", price: 27.99, originalPrice: 40.00, emoji: "🌿", desc: "Premium KSM-66 ashwagandha for stress, energy, and cortisol balance.", requires_rx: false, rating: 4.8, reviews: 389, sku: "SUP-011", inStock: true, tags: ["ashwagandha", "stress", "energy"] },
  { id: 62, name: "Turmeric Curcumin 1000mg (60ct)", category: "supplement", subcategory: "Anti-inflammatory", price: 23.99, originalPrice: 36.00, emoji: "🌿", desc: "Curcumin with black pepper extract for maximum anti-inflammatory benefit.", requires_rx: false, rating: 4.7, reviews: 312, sku: "SUP-012", inStock: true, tags: ["turmeric", "inflammation", "joints"] },
  { id: 63, name: "B-Complex Vitamins (60ct)", category: "supplement", subcategory: "Vitamins", price: 16.99, originalPrice: 26.00, emoji: "💊", desc: "Complete B vitamin complex for energy metabolism and nervous system.", requires_rx: false, rating: 4.8, reviews: 289, sku: "SUP-013", inStock: true, tags: ["B vitamins", "energy", "nerves"] },
  { id: 64, name: "Iron 65mg Ferrous Sulfate (100ct)", category: "supplement", subcategory: "Minerals", price: 8.99, originalPrice: 14.00, emoji: "💊", desc: "High-potency iron supplement for iron deficiency anemia.", requires_rx: false, rating: 4.6, reviews: 198, sku: "SUP-014", inStock: true, tags: ["iron", "anemia", "energy"] },
  { id: 65, name: "CoQ10 200mg (60ct)", category: "supplement", subcategory: "Heart Health", price: 29.99, originalPrice: 44.00, emoji: "❤️", desc: "Ubiquinol CoQ10 for cellular energy production and heart health.", requires_rx: false, rating: 4.8, reviews: 234, sku: "SUP-015", inStock: true, tags: ["CoQ10", "heart", "energy"] },
  { id: 66, name: "Glucosamine Chondroitin (90ct)", category: "supplement", subcategory: "Joint Health", price: 27.99, originalPrice: 41.00, emoji: "🦴", desc: "Triple strength formula for joint comfort and cartilage support.", requires_rx: false, rating: 4.7, reviews: 312, sku: "SUP-016", inStock: true, tags: ["joints", "cartilage", "arthritis"] },
  { id: 67, name: "Elderberry + Zinc Gummies (60ct)", category: "supplement", subcategory: "Immune", price: 19.99, originalPrice: 30.00, emoji: "🍇", desc: "Sambucus elderberry with zinc for immune defense support.", requires_rx: false, rating: 4.8, reviews: 445, sku: "SUP-017", inStock: true, tags: ["elderberry", "immune", "zinc"] },
  { id: 68, name: "Prenatal Vitamins (90ct)", category: "supplement", subcategory: "Women's Health", price: 28.99, originalPrice: 42.00, emoji: "🤱", desc: "Comprehensive prenatal with folate, iron, and DHA for pregnancy.", requires_rx: false, rating: 4.9, reviews: 356, sku: "SUP-018", inStock: true, tags: ["prenatal", "pregnancy", "folate"] },
  { id: 69, name: "L-Glutamine 500g Powder", category: "supplement", subcategory: "Sports Nutrition", price: 32.99, originalPrice: 48.00, emoji: "💪", desc: "Pure L-glutamine for gut health, muscle recovery, and immune function.", requires_rx: false, rating: 4.7, reviews: 223, sku: "SUP-019", inStock: true, tags: ["glutamine", "muscle", "gut"] },
  { id: 70, name: "Alpha Lipoic Acid 600mg (60ct)", category: "supplement", subcategory: "Antioxidant", price: 24.99, originalPrice: 37.00, emoji: "💊", desc: "Powerful antioxidant for nerve health and blood sugar support.", requires_rx: false, rating: 4.7, reviews: 167, sku: "SUP-020", inStock: true, tags: ["antioxidant", "nerves", "blood sugar"] },
  { id: 71, name: "Biotin 10000mcg (60ct)", category: "supplement", subcategory: "Beauty", price: 14.99, originalPrice: 22.00, emoji: "💊", desc: "High-potency biotin for hair growth, nail strength, and skin health.", requires_rx: false, rating: 4.7, reviews: 489, sku: "SUP-021", inStock: true, tags: ["biotin", "hair", "nails"] },
  { id: 72, name: "Whey Protein Isolate 2lb", category: "supplement", subcategory: "Sports Nutrition", price: 44.99, originalPrice: 64.00, emoji: "💪", desc: "90%+ protein whey isolate for muscle building and recovery.", requires_rx: false, rating: 4.8, reviews: 512, sku: "SUP-022", inStock: true, tags: ["protein", "whey", "muscle"] },
  { id: 73, name: "Saw Palmetto 320mg (60ct)", category: "supplement", subcategory: "Men's Health", price: 22.99, originalPrice: 34.00, emoji: "🌿", desc: "Standardized saw palmetto extract for prostate health support.", requires_rx: false, rating: 4.6, reviews: 189, sku: "SUP-023", inStock: true, tags: ["saw palmetto", "prostate", "men"] },
  { id: 74, name: "Maca Root 1000mg (60ct)", category: "supplement", subcategory: "Energy", price: 18.99, originalPrice: 28.00, emoji: "🌿", desc: "Peruvian maca root for energy, mood, and hormonal balance.", requires_rx: false, rating: 4.6, reviews: 145, sku: "SUP-024", inStock: true, tags: ["maca", "energy", "hormones"] },
  { id: 75, name: "Vitamin K2 MK-7 100mcg (60ct)", category: "supplement", subcategory: "Bone Health", price: 19.99, originalPrice: 30.00, emoji: "💊", desc: "Menaquinone-7 for bone mineralization and cardiovascular health.", requires_rx: false, rating: 4.8, reviews: 178, sku: "SUP-025", inStock: true, tags: ["vitamin K2", "bone", "heart"] },

  // ===== MEDICAL DEVICES =====
  { id: 76, name: "Blood Pressure Monitor - Upper Arm", category: "device", subcategory: "Cardiovascular", price: 49.99, originalPrice: 75.00, emoji: "🩺", desc: "Clinically validated automatic BP monitor with large digital display and memory for 60 readings.", requires_rx: false, rating: 4.9, reviews: 578, sku: "DEV-001", inStock: true, tags: ["blood pressure", "heart", "monitor"] },
  { id: 77, name: "Glucose Meter Starter Kit", category: "device", subcategory: "Diabetes Management", price: 34.99, originalPrice: 55.00, emoji: "🩸", desc: "Complete glucose monitoring kit with 50 test strips, lancets, and logbook.", requires_rx: false, rating: 4.8, reviews: 389, sku: "DEV-002", inStock: true, tags: ["glucose", "diabetes", "blood sugar"] },
  { id: 78, name: "Pulse Oximeter - Fingertip", category: "device", subcategory: "Respiratory", price: 24.99, originalPrice: 39.00, emoji: "🔴", desc: "Medical-grade SpO2 and pulse rate monitor. FDA cleared.", requires_rx: false, rating: 4.8, reviews: 467, sku: "DEV-003", inStock: true, tags: ["oxygen", "pulse", "SpO2"] },
  { id: 79, name: "Digital Thermometer", category: "device", subcategory: "General", price: 14.99, originalPrice: 24.00, emoji: "🌡️", desc: "Fast 10-second oral/axillary thermometer with fever alert.", requires_rx: false, rating: 4.8, reviews: 534, sku: "DEV-004", inStock: true, tags: ["thermometer", "fever", "temperature"] },
  { id: 80, name: "Ear Thermometer Infrared", category: "device", subcategory: "General", price: 39.99, originalPrice: 60.00, emoji: "🌡️", desc: "1-second ear/forehead readings. Memory for last 9 readings.", requires_rx: false, rating: 4.7, reviews: 312, sku: "DEV-005", inStock: true, tags: ["thermometer", "infrared", "ear"] },
  { id: 81, name: "Nebulizer Machine Compressor", category: "device", subcategory: "Respiratory", price: 59.99, originalPrice: 89.00, emoji: "💨", desc: "Portable tabletop nebulizer for asthma and respiratory medications.", requires_rx: false, rating: 4.8, reviews: 223, sku: "DEV-006", inStock: true, tags: ["nebulizer", "asthma", "respiratory"] },
  { id: 82, name: "CPAP Cleaning Machine", category: "device", subcategory: "Sleep Apnea", price: 89.99, originalPrice: 130.00, emoji: "😴", desc: "Automated CPAP/BiPAP mask and equipment sanitizer.", requires_rx: false, rating: 4.7, reviews: 156, sku: "DEV-007", inStock: true, tags: ["CPAP", "sleep apnea", "cleaning"] },
  { id: 83, name: "Knee Compression Brace", category: "device", subcategory: "Orthopedics", price: 27.99, originalPrice: 42.00, emoji: "🦵", desc: "Adjustable knee support for arthritis, ACL, and patella pain.", requires_rx: false, rating: 4.7, reviews: 289, sku: "DEV-008", inStock: true, tags: ["knee", "support", "arthritis"] },
  { id: 84, name: "Lumbar Support Back Brace", category: "device", subcategory: "Orthopedics", price: 34.99, originalPrice: 52.00, emoji: "🔙", desc: "Posture-correcting lumbar support for lower back pain relief.", requires_rx: false, rating: 4.6, reviews: 245, sku: "DEV-009", inStock: true, tags: ["back", "lumbar", "posture"] },
  { id: 85, name: "Wrist Splint Carpal Tunnel", category: "device", subcategory: "Orthopedics", price: 19.99, originalPrice: 30.00, emoji: "✋", desc: "Ergonomic wrist brace for carpal tunnel syndrome and tendinitis.", requires_rx: false, rating: 4.7, reviews: 198, sku: "DEV-010", inStock: true, tags: ["wrist", "carpal tunnel", "support"] },
  { id: 86, name: "Digital Scale BMI 400lb Capacity", category: "device", subcategory: "General", price: 29.99, originalPrice: 45.00, emoji: "⚖️", desc: "High-precision body weight and BMI scale with large display.", requires_rx: false, rating: 4.7, reviews: 378, sku: "DEV-011", inStock: true, tags: ["scale", "weight", "BMI"] },
  { id: 87, name: "Portable TENS Unit 16 Modes", category: "device", subcategory: "Pain Management", price: 44.99, originalPrice: 68.00, emoji: "⚡", desc: "Rechargeable TENS/EMS device for muscle pain and rehabilitation.", requires_rx: false, rating: 4.7, reviews: 234, sku: "DEV-012", inStock: true, tags: ["TENS", "pain", "muscle"] },
  { id: 88, name: "First Aid Kit 150-Piece", category: "device", subcategory: "First Aid", price: 24.99, originalPrice: 37.00, emoji: "🩹", desc: "Comprehensive first aid kit for home and travel emergencies.", requires_rx: false, rating: 4.9, reviews: 456, sku: "DEV-013", inStock: true, tags: ["first aid", "emergency", "bandages"] },
  { id: 89, name: "Pill Organizer 7-Day (4 Times)", category: "device", subcategory: "Medication Management", price: 12.99, originalPrice: 20.00, emoji: "💊", desc: "Weekly pill organizer with 4 compartments per day.", requires_rx: false, rating: 4.8, reviews: 389, sku: "DEV-014", inStock: true, tags: ["pill organizer", "medication", "weekly"] },
  { id: 90, name: "Electronic Pill Dispenser", category: "device", subcategory: "Medication Management", price: 64.99, originalPrice: 95.00, emoji: "💊", desc: "Automatic pill dispenser with alarm reminders and 28-slot capacity.", requires_rx: false, rating: 4.7, reviews: 145, sku: "DEV-015", inStock: true, tags: ["pill dispenser", "automatic", "alarm"] },
  { id: 91, name: "Lancets 30G (100ct)", category: "device", subcategory: "Diabetes Management", price: 9.99, originalPrice: 16.00, emoji: "🩸", desc: "Thin 30-gauge lancets for virtually painless glucose testing.", requires_rx: false, rating: 4.8, reviews: 312, sku: "DEV-016", inStock: true, tags: ["lancet", "glucose", "diabetes"] },
  { id: 92, name: "Blood Glucose Test Strips (50ct)", category: "device", subcategory: "Diabetes Management", price: 19.99, originalPrice: 32.00, emoji: "🩸", desc: "Compatible with most major glucometer brands. Fast 5-second results.", requires_rx: false, rating: 4.7, reviews: 267, sku: "DEV-017", inStock: true, tags: ["test strips", "glucose", "diabetes"] },
  { id: 93, name: "Ankle Support Wrap", category: "device", subcategory: "Orthopedics", price: 16.99, originalPrice: 26.00, emoji: "🦶", desc: "Compression ankle brace for sprains and athletic support.", requires_rx: false, rating: 4.6, reviews: 189, sku: "DEV-018", inStock: true, tags: ["ankle", "sprain", "compression"] },
  { id: 94, name: "Hot & Cold Therapy Pack", category: "device", subcategory: "Pain Management", price: 14.99, originalPrice: 23.00, emoji: "🧊", desc: "Reusable gel pack for heat and cold therapy. Flexible when frozen.", requires_rx: false, rating: 4.7, reviews: 223, sku: "DEV-019", inStock: true, tags: ["hot cold", "therapy", "pain"] },
  { id: 95, name: "Compression Socks (3 pairs)", category: "device", subcategory: "Cardiovascular", price: 24.99, originalPrice: 37.00, emoji: "🧦", desc: "20-30 mmHg graduated compression socks for circulation and swelling.", requires_rx: false, rating: 4.8, reviews: 356, sku: "DEV-020", inStock: true, tags: ["compression", "circulation", "socks"] },

  // ===== OTHER / SPECIALTY =====
  { id: 96, name: "Hydrogen Peroxide 3% (32oz)", category: "other", subcategory: "First Aid", price: 4.99, originalPrice: 8.00, emoji: "🧪", desc: "Topical antiseptic for wound care and oral hygiene.", requires_rx: false, rating: 4.7, reviews: 234, sku: "OTH-001", inStock: true, tags: ["antiseptic", "wound", "peroxide"] },
  { id: 97, name: "Isopropyl Alcohol 91% (32oz)", category: "other", subcategory: "First Aid", price: 5.99, originalPrice: 9.00, emoji: "🧪", desc: "Medical-grade isopropyl alcohol for disinfection and wound care.", requires_rx: false, rating: 4.8, reviews: 345, sku: "OTH-002", inStock: true, tags: ["alcohol", "disinfectant", "antiseptic"] },
  { id: 98, name: "Wound Care Gauze Pads (25ct)", category: "other", subcategory: "Wound Care", price: 7.99, originalPrice: 12.00, emoji: "🩹", desc: "Sterile 4x4 gauze pads for wound dressing and wound care.", requires_rx: false, rating: 4.8, reviews: 156, sku: "OTH-003", inStock: true, tags: ["gauze", "wound", "sterile"] },
  { id: 99, name: "Elastic Bandage Wrap 3\" (6ct)", category: "other", subcategory: "Wound Care", price: 9.99, originalPrice: 15.00, emoji: "🩹", desc: "Self-adherent elastic compression bandage for sprains and splints.", requires_rx: false, rating: 4.7, reviews: 178, sku: "OTH-004", inStock: true, tags: ["bandage", "wrap", "sprain"] },
  { id: 100, name: "Nitrile Exam Gloves (100ct)", category: "other", subcategory: "PPE", price: 14.99, originalPrice: 22.00, emoji: "🧤", desc: "Powder-free nitrile medical examination gloves. Latex-free.", requires_rx: false, rating: 4.8, reviews: 289, sku: "OTH-005", inStock: true, tags: ["gloves", "nitrile", "PPE"] },
  { id: 101, name: "N95 Respirator Masks (10ct)", category: "other", subcategory: "PPE", price: 16.99, originalPrice: 25.00, emoji: "😷", desc: "NIOSH-approved N95 respirator masks for airborne particle protection.", requires_rx: false, rating: 4.8, reviews: 312, sku: "OTH-006", inStock: true, tags: ["N95", "mask", "PPE"] },
  { id: 102, name: "Vitamin A 10000 IU (100ct)", category: "supplement", subcategory: "Vitamins", price: 10.99, originalPrice: 17.00, emoji: "💊", desc: "Retinol vitamin A for vision, immune function, and skin health.", requires_rx: false, rating: 4.6, reviews: 145, sku: "SUP-026", inStock: true, tags: ["vitamin A", "vision", "skin"] },
  { id: 103, name: "Echinacea 400mg (90ct)", category: "supplement", subcategory: "Immune", price: 15.99, originalPrice: 24.00, emoji: "🌿", desc: "Echinacea purpurea extract to shorten duration of colds.", requires_rx: false, rating: 4.6, reviews: 189, sku: "SUP-027", inStock: true, tags: ["echinacea", "immune", "cold"] },
  { id: 104, name: "Spirulina Powder 500g", category: "supplement", subcategory: "Superfoods", price: 27.99, originalPrice: 42.00, emoji: "🌿", desc: "Certified organic spirulina powder, rich in protein and B12.", requires_rx: false, rating: 4.7, reviews: 234, sku: "SUP-028", inStock: true, tags: ["spirulina", "superfood", "protein"] },
  { id: 105, name: "Quercetin + Bromelain 500mg (60ct)", category: "supplement", subcategory: "Anti-inflammatory", price: 22.99, originalPrice: 34.00, emoji: "💊", desc: "Natural bioflavonoid quercetin with bromelain for immune and allergy support.", requires_rx: false, rating: 4.7, reviews: 167, sku: "SUP-029", inStock: true, tags: ["quercetin", "allergy", "inflammation"] },
  { id: 106, name: "Resveratrol 500mg (60ct)", category: "supplement", subcategory: "Anti-aging", price: 28.99, originalPrice: 43.00, emoji: "🍷", desc: "Trans-resveratrol antioxidant for longevity and cardiovascular support.", requires_rx: false, rating: 4.7, reviews: 145, sku: "SUP-030", inStock: true, tags: ["resveratrol", "antioxidant", "longevity"] },
  { id: 107, name: "L-Theanine 200mg (60ct)", category: "supplement", subcategory: "Mood/Stress", price: 16.99, originalPrice: 26.00, emoji: "🍵", desc: "Green tea amino acid for calm focus and stress reduction.", requires_rx: false, rating: 4.8, reviews: 289, sku: "SUP-031", inStock: true, tags: ["L-theanine", "stress", "focus"] },
  { id: 108, name: "Creatine Monohydrate 500g", category: "supplement", subcategory: "Sports Nutrition", price: 29.99, originalPrice: 44.00, emoji: "💪", desc: "Pure micronized creatine monohydrate for strength and muscle performance.", requires_rx: false, rating: 4.9, reviews: 478, sku: "SUP-032", inStock: true, tags: ["creatine", "strength", "muscle"] },
  { id: 109, name: "Valerian Root 450mg (60ct)", category: "supplement", subcategory: "Sleep", price: 14.99, originalPrice: 22.00, emoji: "🌿", desc: "Traditional sleep herb for falling asleep faster and improving sleep quality.", requires_rx: false, rating: 4.5, reviews: 198, sku: "SUP-033", inStock: true, tags: ["valerian", "sleep", "insomnia"] },
  { id: 110, name: "Milk Thistle 175mg (90ct)", category: "supplement", subcategory: "Liver Health", price: 17.99, originalPrice: 27.00, emoji: "🌿", desc: "Silymarin extract for liver detox and hepatoprotection.", requires_rx: false, rating: 4.7, reviews: 178, sku: "SUP-034", inStock: true, tags: ["milk thistle", "liver", "detox"] },
  { id: 111, name: "DHEA 25mg (60ct)", category: "supplement", subcategory: "Hormones", price: 15.99, originalPrice: 24.00, emoji: "💊", desc: "Adrenal hormone precursor for energy, mood, and vitality.", requires_rx: false, rating: 4.5, reviews: 123, sku: "SUP-035", inStock: true, tags: ["DHEA", "hormone", "energy"] },
  { id: 112, name: "Hyaluronic Acid 100mg (60ct)", category: "supplement", subcategory: "Joint/Skin", price: 19.99, originalPrice: 30.00, emoji: "💊", desc: "Oral hyaluronic acid for joint lubrication and skin hydration.", requires_rx: false, rating: 4.7, reviews: 234, sku: "SUP-036", inStock: true, tags: ["hyaluronic acid", "skin", "joints"] },
  { id: 113, name: "5-HTP 100mg (60ct)", category: "supplement", subcategory: "Mood/Sleep", price: 18.99, originalPrice: 28.00, emoji: "💊", desc: "Serotonin precursor for mood, sleep, and appetite regulation.", requires_rx: false, rating: 4.6, reviews: 189, sku: "SUP-037", inStock: true, tags: ["5-HTP", "serotonin", "mood"] },
  { id: 114, name: "Ginkgo Biloba 120mg (60ct)", category: "supplement", subcategory: "Brain Health", price: 16.99, originalPrice: 26.00, emoji: "🌿", desc: "Standardized ginkgo extract for memory, focus, and circulation.", requires_rx: false, rating: 4.6, reviews: 198, sku: "SUP-038", inStock: true, tags: ["ginkgo", "memory", "brain"] },
  { id: 115, name: "Selenium 200mcg (90ct)", category: "supplement", subcategory: "Antioxidant", price: 11.99, originalPrice: 18.00, emoji: "💊", desc: "Trace mineral antioxidant for thyroid function and immune health.", requires_rx: false, rating: 4.7, reviews: 145, sku: "SUP-039", inStock: true, tags: ["selenium", "thyroid", "antioxidant"] },
  { id: 116, name: "Iodine 12.5mg (60ct)", category: "supplement", subcategory: "Thyroid", price: 12.99, originalPrice: 20.00, emoji: "💊", desc: "Lugol's iodine tablet for thyroid support and iodine deficiency.", requires_rx: false, rating: 4.5, reviews: 112, sku: "SUP-040", inStock: true, tags: ["iodine", "thyroid", "mineral"] },

  // ===== MORE DEVICES =====
  { id: 117, name: "Stethoscope Dual Head", category: "device", subcategory: "Diagnostic", price: 34.99, originalPrice: 52.00, emoji: "🩺", desc: "Dual-head stethoscope for cardiac and lung auscultation. For home care.", requires_rx: false, rating: 4.7, reviews: 134, sku: "DEV-021", inStock: true, tags: ["stethoscope", "cardiac", "diagnostic"] },
  { id: 118, name: "Medical Scale Pediatric", category: "device", subcategory: "Diagnostic", price: 54.99, originalPrice: 80.00, emoji: "⚖️", desc: "Digital infant and toddler scale accurate to 0.01 lbs.", requires_rx: false, rating: 4.6, reviews: 89, sku: "DEV-022", inStock: true, tags: ["scale", "pediatric", "infant"] },
  { id: 119, name: "Shoulder Immobilizer Sling", category: "device", subcategory: "Orthopedics", price: 22.99, originalPrice: 34.00, emoji: "💪", desc: "Adjustable shoulder sling for rotator cuff and post-surgery recovery.", requires_rx: false, rating: 4.6, reviews: 112, sku: "DEV-023", inStock: true, tags: ["shoulder", "sling", "recovery"] },
  { id: 120, name: "Cervical Foam Collar", category: "device", subcategory: "Orthopedics", price: 18.99, originalPrice: 28.00, emoji: "🔄", desc: "Soft cervical collar for neck pain and whiplash support.", requires_rx: false, rating: 4.5, reviews: 98, sku: "DEV-024", inStock: true, tags: ["neck", "cervical", "collar"] },

  // ===== MORE RX =====
  { id: 121, name: "Topiramate 25mg", category: "rx", subcategory: "Neurology", price: 23.99, originalPrice: 37.00, emoji: "💊", desc: "Anticonvulsant for epilepsy and migraine prevention.", requires_rx: true, rating: 4.5, reviews: 87, sku: "RX-026", inStock: true, tags: ["migraine", "epilepsy", "anticonvulsant"] },
  { id: 122, name: "Duloxetine 30mg", category: "rx", subcategory: "Mental Health", price: 24.99, originalPrice: 38.00, emoji: "💊", desc: "SNRI for depression, anxiety, and neuropathic pain.", requires_rx: true, rating: 4.6, reviews: 134, sku: "RX-027", inStock: true, tags: ["SNRI", "depression", "pain"] },
  { id: 123, name: "Bupropion 150mg SR", category: "rx", subcategory: "Mental Health", price: 26.99, originalPrice: 40.00, emoji: "💊", desc: "Antidepressant also used for smoking cessation.", requires_rx: true, rating: 4.7, reviews: 145, sku: "RX-028", inStock: true, tags: ["antidepressant", "quit smoking"] },
  { id: 124, name: "Trazodone 50mg", category: "rx", subcategory: "Mental Health", price: 15.99, originalPrice: 25.00, emoji: "💊", desc: "Antidepressant also prescribed for insomnia.", requires_rx: true, rating: 4.5, reviews: 112, sku: "RX-029", inStock: true, tags: ["sleep", "insomnia", "antidepressant"] },
  { id: 125, name: "Propranolol 10mg", category: "rx", subcategory: "Cardiology", price: 13.99, originalPrice: 22.00, emoji: "💊", desc: "Beta-blocker for hypertension, angina, and performance anxiety.", requires_rx: true, rating: 4.6, reviews: 123, sku: "RX-030", inStock: true, tags: ["beta-blocker", "anxiety", "heart"] },

  // ===== MORE OTC =====
  { id: 126, name: "Phenylephrine Tablets 10mg (24ct)", category: "otc", subcategory: "Cold & Flu", price: 8.99, originalPrice: 14.00, emoji: "💊", desc: "Oral decongestant for nasal and sinus congestion.", requires_rx: false, rating: 4.5, reviews: 189, sku: "OTC-026", inStock: true, tags: ["decongestant", "sinus", "cold"] },
  { id: 127, name: "Pseudoephedrine 30mg (24ct)", category: "otc", subcategory: "Cold & Flu", price: 9.99, originalPrice: 15.00, emoji: "💊", desc: "Maximum-strength nasal decongestant. Available behind the counter.", requires_rx: false, rating: 4.7, reviews: 234, sku: "OTC-027", inStock: true, tags: ["decongestant", "pseudoephedrine", "sinus"] },
  { id: 128, name: "Bismuth Subsalicylate (30 doses)", category: "otc", subcategory: "Digestive Health", price: 9.99, originalPrice: 15.00, emoji: "💊", desc: "Pink bismuth for upset stomach, indigestion, and diarrhea.", requires_rx: false, rating: 4.7, reviews: 267, sku: "OTC-028", inStock: true, tags: ["stomach", "diarrhea", "Pepto"] },
  { id: 129, name: "Bacitracin Zinc Ointment 1oz", category: "otc", subcategory: "First Aid", price: 6.99, originalPrice: 10.00, emoji: "🧴", desc: "Single-antibiotic ointment for minor cuts and abrasions.", requires_rx: false, rating: 4.6, reviews: 156, sku: "OTC-029", inStock: true, tags: ["antibiotic", "wound", "first aid"] },
  { id: 130, name: "Wart Remover Salicylic Acid 17%", category: "otc", subcategory: "Skin", price: 8.99, originalPrice: 13.00, emoji: "🧴", desc: "Maximum-strength wart remover liquid for plantar and common warts.", requires_rx: false, rating: 4.5, reviews: 134, sku: "OTC-030", inStock: true, tags: ["wart", "salicylic acid", "skin"] },

  // ===== FINAL 20 MIXED =====
  { id: 131, name: "NMN 250mg (60ct)", category: "supplement", subcategory: "Anti-aging", price: 44.99, originalPrice: 65.00, emoji: "💊", desc: "Nicotinamide mononucleotide for NAD+ support and cellular aging.", requires_rx: false, rating: 4.8, reviews: 289, sku: "SUP-041", inStock: true, tags: ["NMN", "NAD+", "anti-aging"] },
  { id: 132, name: "Berberine 500mg (90ct)", category: "supplement", subcategory: "Metabolic", price: 29.99, originalPrice: 44.00, emoji: "🌿", desc: "Alkaloid compound for blood sugar, cholesterol, and gut health.", requires_rx: false, rating: 4.8, reviews: 312, sku: "SUP-042", inStock: true, tags: ["berberine", "blood sugar", "metabolic"] },
  { id: 133, name: "NAC N-Acetyl Cysteine 600mg (60ct)", category: "supplement", subcategory: "Antioxidant", price: 18.99, originalPrice: 28.00, emoji: "💊", desc: "Glutathione precursor for liver and lung health support.", requires_rx: false, rating: 4.7, reviews: 234, sku: "SUP-043", inStock: true, tags: ["NAC", "glutathione", "liver"] },
  { id: 134, name: "Lithium Orotate 5mg (60ct)", category: "supplement", subcategory: "Brain Health", price: 15.99, originalPrice: 24.00, emoji: "💊", desc: "Micro-dose lithium for mood stability and neuroprotection.", requires_rx: false, rating: 4.6, reviews: 145, sku: "SUP-044", inStock: true, tags: ["lithium", "mood", "brain"] },
  { id: 135, name: "Digestive Enzymes Blend (60ct)", category: "supplement", subcategory: "Digestive", price: 23.99, originalPrice: 35.00, emoji: "💊", desc: "Full-spectrum enzymes for protein, fat, and carb digestion.", requires_rx: false, rating: 4.7, reviews: 189, sku: "SUP-045", inStock: true, tags: ["enzymes", "digestion", "bloating"] },
  { id: 136, name: "Electrolyte Powder Packets (30ct)", category: "supplement", subcategory: "Hydration", price: 22.99, originalPrice: 34.00, emoji: "💧", desc: "Zero-sugar electrolytes with sodium, potassium, magnesium.", requires_rx: false, rating: 4.8, reviews: 345, sku: "SUP-046", inStock: true, tags: ["electrolytes", "hydration", "sports"] },
  { id: 137, name: "Manuka Honey 250g MGO 400", category: "supplement", subcategory: "Natural", price: 34.99, originalPrice: 52.00, emoji: "🍯", desc: "Certified MGO 400+ New Zealand manuka honey for gut and immune health.", requires_rx: false, rating: 4.8, reviews: 178, sku: "SUP-047", inStock: true, tags: ["manuka", "honey", "natural"] },
  { id: 138, name: "Cough Drops Honey Lemon (30ct)", category: "otc", subcategory: "Cold & Flu", price: 5.99, originalPrice: 9.00, emoji: "🍬", desc: "Soothing honey lemon throat drops for cough and sore throat.", requires_rx: false, rating: 4.6, reviews: 289, sku: "OTC-031", inStock: true, tags: ["cough", "throat", "honey"] },
  { id: 139, name: "Sore Throat Spray", category: "otc", subcategory: "Cold & Flu", price: 7.99, originalPrice: 12.00, emoji: "💨", desc: "Benzocaine throat spray for fast-acting sore throat relief.", requires_rx: false, rating: 4.5, reviews: 198, sku: "OTC-032", inStock: true, tags: ["sore throat", "spray", "benzocaine"] },
  { id: 140, name: "Electrolyte Oral Rehydration Packets (10ct)", category: "otc", subcategory: "Hydration", price: 10.99, originalPrice: 17.00, emoji: "💧", desc: "WHO-formula oral rehydration salts for dehydration from illness.", requires_rx: false, rating: 4.7, reviews: 167, sku: "OTC-033", inStock: true, tags: ["rehydration", "electrolytes", "dehydration"] },
  { id: 141, name: "Triamcinolone Acetonide Cream 0.1%", category: "rx", subcategory: "Skin", price: 18.99, originalPrice: 29.00, emoji: "🧴", desc: "Prescription-strength topical corticosteroid for inflammatory skin conditions.", requires_rx: true, rating: 4.6, reviews: 112, sku: "RX-031", inStock: true, tags: ["steroid cream", "eczema", "skin"] },
  { id: 142, name: "Montelukast 10mg", category: "rx", subcategory: "Respiratory", price: 20.99, originalPrice: 32.00, emoji: "💊", desc: "Leukotriene receptor antagonist for asthma and allergic rhinitis.", requires_rx: true, rating: 4.7, reviews: 134, sku: "RX-032", inStock: true, tags: ["asthma", "allergy", "leukotriene"] },
  { id: 143, name: "Oral Irrigation Device", category: "device", subcategory: "Dental", price: 39.99, originalPrice: 60.00, emoji: "🦷", desc: "Water flosser for gum health and oral hygiene. Multiple pressure settings.", requires_rx: false, rating: 4.8, reviews: 378, sku: "DEV-025", inStock: true, tags: ["dental", "water flosser", "oral care"] },
  { id: 144, name: "Heating Pad Electric 12x24\"", category: "device", subcategory: "Pain Management", price: 29.99, originalPrice: 45.00, emoji: "🔥", desc: "Moist/dry electric heating pad with auto shut-off for back and joint pain.", requires_rx: false, rating: 4.8, reviews: 312, sku: "DEV-026", inStock: true, tags: ["heating pad", "pain", "back"] },
  { id: 145, name: "Portable Ultrasonic Humidifier", category: "device", subcategory: "Respiratory", price: 34.99, originalPrice: 52.00, emoji: "💨", desc: "Quiet cool mist humidifier for congestion and dry air relief.", requires_rx: false, rating: 4.7, reviews: 245, sku: "DEV-027", inStock: true, tags: ["humidifier", "congestion", "dry air"] },
  { id: 146, name: "Sildenafil 20mg (6ct)", category: "rx", subcategory: "Urology", price: 28.99, originalPrice: 44.00, emoji: "💊", desc: "PDE5 inhibitor for erectile dysfunction. Generic Viagra equivalent.", requires_rx: true, rating: 4.7, reviews: 245, sku: "RX-033", inStock: true, tags: ["ED", "erectile dysfunction", "sildenafil"] },
  { id: 147, name: "Tadalafil 10mg (6ct)", category: "rx", subcategory: "Urology", price: 32.99, originalPrice: 49.00, emoji: "💊", desc: "Long-acting PDE5 inhibitor for ED. Generic Cialis equivalent.", requires_rx: true, rating: 4.8, reviews: 289, sku: "RX-034", inStock: true, tags: ["ED", "tadalafil", "Cialis"] },
  { id: 148, name: "Tretinoin Cream 0.025%", category: "rx", subcategory: "Dermatology", price: 26.99, originalPrice: 40.00, emoji: "🧴", desc: "Retinoid for acne treatment and anti-aging wrinkle therapy.", requires_rx: true, rating: 4.8, reviews: 312, sku: "RX-035", inStock: true, tags: ["acne", "retinoid", "anti-aging"] },
  { id: 149, name: "Spironolactone 25mg", category: "rx", subcategory: "Dermatology/Cardio", price: 16.99, originalPrice: 26.00, emoji: "💊", desc: "Potassium-sparing diuretic for hormonal acne and blood pressure.", requires_rx: true, rating: 4.6, reviews: 134, sku: "RX-036", inStock: true, tags: ["acne", "hormone", "diuretic"] },
  { id: 150, name: "Emergency Contraceptive Pill", category: "otc", subcategory: "Women's Health", price: 39.99, originalPrice: 55.00, emoji: "💊", desc: "Levonorgestrel emergency contraceptive. Most effective within 72 hours.", requires_rx: false, rating: 4.7, reviews: 198, sku: "OTC-034", inStock: true, tags: ["contraceptive", "emergency", "women"] }
];

const CATEGORIES = [
  { id: "all", label: "All Products", icon: "🏥", count: 150 },
  { id: "rx", label: "Prescription (Rx)", icon: "💊", count: PROMEDIC_PRODUCTS.filter(p => p.category === "rx").length },
  { id: "otc", label: "OTC", icon: "🩹", count: PROMEDIC_PRODUCTS.filter(p => p.category === "otc").length },
  { id: "supplement", label: "Supplements", icon: "🌿", count: PROMEDIC_PRODUCTS.filter(p => p.category === "supplement").length },
  { id: "device", label: "Medical Devices", icon: "🩺", count: PROMEDIC_PRODUCTS.filter(p => p.category === "device").length },
  { id: "other", label: "Other", icon: "🧪", count: PROMEDIC_PRODUCTS.filter(p => p.category === "other").length }
];

function getCategoryBadge(category) {
  switch(category) {
    case "rx": return '<span class="badge badge-rx">Rx Required</span>';
    case "otc": return '<span class="badge badge-otc">OTC</span>';
    case "supplement": return '<span class="badge badge-supplement">Supplement</span>';
    case "device": return '<span class="badge badge-device">Medical Device</span>';
    default: return '<span class="badge badge-otc">Other</span>';
  }
}

function renderProductCard(product) {
  const savings = product.originalPrice ? Math.round(((product.originalPrice - product.price) / product.originalPrice) * 100) : 0;
  return `
    <article class="product-card" data-id="${product.id}" data-category="${product.category}" itemscope itemtype="https://schema.org/Product">
      <div class="product-image">
        <span itemprop="image" aria-hidden="true">${product.emoji}</span>
        ${savings > 0 ? `<span style="position:absolute;top:10px;right:44px;background:#dc2626;color:white;font-size:11px;font-weight:700;padding:3px 7px;border-radius:4px;">-${savings}%</span>` : ''}
        <button class="product-wishlist" aria-label="Add ${product.name} to wishlist" onclick="toggleWishlist(${product.id})">&#9825;</button>
      </div>
      <div class="product-body">
        <h3 class="product-name" itemprop="name">${product.name}</h3>
        <p class="product-desc" itemprop="description">${product.desc}</p>
        <div class="product-footer">
          <div>
            <span class="product-price" itemprop="price" content="${product.price}">$${product.price.toFixed(2)}</span>
            ${product.originalPrice ? `<span class="product-price-orig">$${product.originalPrice.toFixed(2)}</span>` : ''}
          </div>
          <button class="add-to-cart" onclick="addToCart(${product.id})" aria-label="Add ${product.name} to cart">
            <svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>
            Add
          </button>
        </div>
      </div>
    </article>
  `;
}

if (typeof module !== 'undefined') module.exports = { PROMEDIC_PRODUCTS, CATEGORIES };
